// scripts/OLSD134R/file-naming.js
// File naming rules for the OLSD134R batch.
// This module names the report file generated by the batch; the report has no input file.
//
//   MYOLSD134R<batch date YYYYMMDD>.txt
// Where:
//   - 'MY' is the environment prefix (MY-dev)
//   - 'OLSD134R' is the report ID (EOD Batch flow v1.10 row 80: batch = OLSDR134)
//   - <batch date> is the batch_date.batch_date value
//
// OLSDB009 input files used for data seeding are not named here. They follow the rules
// in scripts/OLSDB009/file-generator.js and are reused without renaming.

import path from 'path';
import { CONFIG } from './test-data.js';

/** MYOLSD134R20260922.txt */
export function reportFileName(batchDateYmd) {
  return `${CONFIG.report.prefix}${batchDateYmd}${CONFIG.report.extension}`;
}

/**
 * Report file pattern, independent of the environment or country code:
 *   *OLSD134R20260922*.txt
 */
export function reportFileGlob(batchDateYmd) {
  const reportId = CONFIG.report.reportId || 'OLSD134R';
  return `*${reportId}${batchDateYmd}*.txt`;
}

/** reports\OLSD134R\<report file downloaded from the server> */
export function reportLocalPathForName(fileName) {
  return path.join(CONFIG.report.localDir, fileName);
}

/** /apps/MY-dev/OE/cls/USER_OUTPUT/OLSD134R/MYOLSD134R20260922.txt */
export function reportRemotePath(batchDateYmd) {
  return `${CONFIG.report.remoteDir}/${reportFileName(batchDateYmd)}`;
}

/** reports\OLSD134R\MYOLSD134R20260922.txt (local path) */
export function reportLocalPath(batchDateYmd) {
  return path.join(CONFIG.report.localDir, reportFileName(batchDateYmd));
}

/**
 * Parse the report file name and return its batch date in YYYYMMDD format.
 * Used to find the latest report when the batch date is not known.
 * @returns {{batchDate: string}|null}
 */
export function parseReportFileName(fileName) {
  const reportId = CONFIG.report.reportId || 'OLSD134R';
  const pattern = new RegExp(
    `^([A-Za-z]{0,4})${reportId}(\\d{8})(?:_\\d{8})?\\${CONFIG.report.extension}$`
  );
  const m = String(fileName).trim().match(pattern);
  return m ? { envCode: m[1] || null, batchDate: m[2] } : null;
}

/** Return the file path in the local staging directory. */
export function stagingPath(fileName) {
  return path.join(CONFIG.winscp.localPath, fileName);
}
